services:
  - type: web
    name: operator-api
    env: docker
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      # --- Browser & Headless ---
      - key: HEADLESS
        value: "1"
      - key: BROWSER_CHANNEL
        value: "chrome"   # prefer Chrome (Playwright will fall back to Chromium in your code)
      # - key: BROWSER
      #   value: "chromium"  # not needed; your code launches chromium with channel=chrome

      # --- Model / Hugging Face ---
      - key: MODEL_ID
        value: "xenon111/neur-0.0-full"   # change if different
      - key: HF_HOME
        value: "/data/.cache/huggingface"
      - key: HF_HUB_ENABLE_HF_TRANSFER
        value: "1"
      # If your model repo is private, uncomment:
      # - key: HF_TOKEN
      #   sync: false

      # --- Optional Behavior Flags ---
      - key: MAX_AGENT_TURNS
        value: "6"
      - key: GEN_MAX_CONCURRENCY
        value: "2"

      # --- Misc Safety / Debug ---
      - key: TRANSFORMERS_NO_REMOTE_CODE
        value: "0"
